### ISSUE TITLE
VIO 

### ISSUE THREAD

**Issue by koendv** [wuxx/nanoCH32V305#1]
Nice board. I have a request. 
CH32V30x is one of the few cheap processors with a separate VIO pin. 
Perhaps allow connecting VIO to other voltages than 3.3V?
Thank you.

**Comment by wuxx** [comment]
Yes, you can control the IO level through VIO. For details, please refer to the datasheet.

**Comment by koendv** [comment]
Thank you for your answer. 
Yes, it is possible to have separate VIO and 3.3V. But how to separate VIO and 3.3V on the nanoCH32V305?
It would be easier if VIO and 3.3V were connected like this, with a closed solder bridge:
![solder_bridge](https://github.com/wuxx/nanoCH32V305/assets/2753612/30880bf3-872c-4370-b52f-5366ff046251)
A solder bridge does not cost money.

**Comment by wuxx** [comment]
Okay, we will consider modifying it to a VIO configurable method in the next version.

**Comment by koendv** [comment]
Thank you. This would be most helpful.
