### ISSUE TITLE
Is it really belong to CH32V305?

### ISSUE THREAD

**Issue by doorferi** [wuxx/nanoCH32V305#2]
How does this project correlate to CH32V305? All of the code refered here is belong to CH32V203. That is different RISC-V core ...

**Comment by wuxx** [comment]
Hello, where did you see the information about 203? 305 and 203 are different chips.

**Comment by doorferi** [comment]
Yes it is, they are different. Have you ever read the "How to use" chapter included into readme? All of the pictures highlited and refer to 203!

**Comment by wuxx** [comment]
Okay, it’s actually the same series, and the use of MRS is almost the same....

**Comment by doorferi** [comment]
Now is the same series :D ... nice ... And your comment how does it help?

**Comment by wuxx** [comment]
OK. I will fix the to avoid misunderstandings later

**Comment by doorferi** [comment]
Thank you for your help! It is much better and easier follow it in this way.
